-- 1. Crear la tabla padre 'users' que contendrá los datos comunes
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       tenant_id BIGINT NOT NULL,
                       name VARCHAR(100) NOT NULL,
                       last_name VARCHAR(100) NOT NULL,
                       phone_number VARCHAR(20) NOT NULL,
                       email VARCHAR(100) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT uk_users_email UNIQUE (email)
);

-- 2. Crear la tabla hija 'user_admins'
CREATE TABLE user_admins (
                             id BIGINT NOT NULL, -- Este ID es FK a users(id)
                             user_position VARCHAR(30) NOT NULL,
                             active BOOLEAN NOT NULL DEFAULT TRUE,
                             CONSTRAINT pk_user_admins PRIMARY KEY (id)
);

-- 3. Crear la tabla hija 'users_clients'
CREATE TABLE users_clients (
                               id BIGINT NOT NULL, -- Este ID es FK a users(id)
                               CONSTRAINT pk_users_clients PRIMARY KEY (id)
);

-- 4. Establecer las llaves foráneas
-- Relación de herencia (Hija -> Padre)
ALTER TABLE user_admins
    ADD CONSTRAINT fk_user_admins_on_users FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE users_clients
    ADD CONSTRAINT fk_users_clients_on_users FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE;

-- Relación con el Tenant (Padre -> Tenant)
ALTER TABLE users
    ADD CONSTRAINT fk_users_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

-- 5. Crear índice para búsquedas por email (vital para el login)
CREATE INDEX idx_users_email ON users(email);